### ISSUE TITLE
No TypeAdapter for class 

### ISSUE THREAD

**Issue by vastsea88** [Tickaroo/tikxml#151]
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

 implementation 'com.tickaroo.tikxml:annotation:0.9.0_11-SNAPSHOT'
 implementation 'com.tickaroo.tikxml:core:0.9.0_11-SNAPSHOT'
 annotationProcessor 'com.tickaroo.tikxml:processor:0.9.0_11-SNAPSHOT'

val build = TikXml.Builder().build()
val buffer = assets.open("strings.xml").source().buffer()
val read = build.read<TextRes>(buffer, TextResTypeAdapter::class.java)
read?.strings!![0].let { Log.d("ddd", it.name) }

class TextResTypeAdapter : TypeAdapter<TextRes> {
    override fun fromXml(
        reader: XmlReader?,
        config: TikXmlConfig?,
        isGenericList: Boolean
    ): TextRes {
        Log.d("ddd", reader!!.nextTextContent())
        return TextRes()
    }

    override fun toXml(
        writer: XmlWriter?,
        config: TikXmlConfig?,
        value: TextRes?,
        overridingXmlElementTagName: String?
    ) {

    }
}

Caused by: com.tickaroo.tikxml.TypeAdapterNotFoundException: No TypeAdapter for class com.butterfly_forest.myhanlp.TextResTypeAdapter found. Expected name of the type adapter is com.butterfly_forest.myhanlp.TextResTypeAdapter$$TypeAdapter
        at com.tickaroo.tikxml.TypeAdapters.get(TypeAdapters.java:139)
        at com.tickaroo.tikxml.TypeAdapters.get(TypeAdapters.java:63)
        at com.tickaroo.tikxml.TikXmlConfig.getTypeAdapter(TikXmlConfig.java:84)
        at com.tickaroo.tikxml.TikXml.read(TikXml.java:113)
        at com.butterfly_forest.myhanlp.MainActivity.onCreate(MainActivity.kt:28)
        at android.app.Activity.performCreate(Activity.java:7963)
        at android.app.Activity.performCreate(Activity.java:7952)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)

**Comment by sockeqwe** [comment]
Hello,
I think you need to replace

```
annotationProcessor 'com.tickaroo.tikxml:processor:0.9.0_11-SNAPSHOT'
```

with 

```
kapt 'com.tickaroo.tikxml:processor:0.9.0_11-SNAPSHOT'
```

Does that solve your problem?

**Comment by sockeqwe** [comment]
Closing this issue because inactive
